//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARK.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ARK.UI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершение работы ядра....
        /// </summary>
        public static string App_Exiting {
            get {
                return ResourceManager.GetString("App_Exiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запуск ядра Automated Response Kernel....
        /// </summary>
        public static string App_Starting {
            get {
                return ResourceManager.GetString("App_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        public static string Tray_Exit {
            get {
                return ResourceManager.GetString("Tray_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть оверлей.
        /// </summary>
        public static string Tray_OverlayToShow {
            get {
                return ResourceManager.GetString("Tray_OverlayToShow", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Критическая ошибка.
        /// </summary>
        public static string Error_CriticalTitle {
            get {
                return ResourceManager.GetString("Error_CriticalTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла непредвиденная ошибка...
        /// </summary>
        public static string Error_CriticalMessage {
            get {
                return ResourceManager.GetString("Error_CriticalMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   ARK: ЯДРО АКТИВНО
        /// </summary>
        public static string Tray_StatusActive {
            get {
                return ResourceManager.GetString("Tray_StatusActive", resourceCulture);
            }
        }

        /// <summary>
        ///   ARK: ЯДРО НА ПАУЗЕ
        /// </summary>
        public static string Tray_StatusPause {
            get {
                return ResourceManager.GetString("Tray_StatusPause", resourceCulture);
            }
        }

        /// <summary>
        ///   Отображать оверлей
        /// </summary>
        public static string Tray_ToggleOverlay {
            get {
                return ResourceManager.GetString("Tray_ToggleOverlay", resourceCulture);
            }
        }

        /// <summary>
        ///   Панель управления
        /// </summary>
        public static string Tray_OpenDashboard {
            get {
                return ResourceManager.GetString("Tray_OpenDashboard", resourceCulture);
            }
        }

        /// <summary>Сеть: ПОДКЛЮЧЕНО / Network: CONNECTED</summary>
        public static string Tray_NetworkConnected {
            get { return ResourceManager.GetString("Tray_NetworkConnected", resourceCulture); }
        }

        /// <summary>Сеть: РАЗОРВАНО / Network: DISCONNECTED</summary>
        public static string Tray_NetworkDisconnected {
            get { return ResourceManager.GetString("Tray_NetworkDisconnected", resourceCulture); }
        }

        /// <summary>Перезапустить ARK / Restart ARK</summary>
        public static string Tray_RestartApp {
            get { return ResourceManager.GetString("Tray_RestartApp", resourceCulture); }
        }

        /// <summary>Язык: РУССКИЙ / Language: ENGLISH</summary>
        public static string Tray_ToggleLanguage {
            get { return ResourceManager.GetString("Tray_ToggleLanguage", resourceCulture); }
        }

        /// <summary>Очистить файлы логов / Clear Log Files</summary>
        public static string Tray_ClearLogs {
            get { return ResourceManager.GetString("Tray_ClearLogs", resourceCulture); }
        }

        /// <summary>Запускать при старте Windows / Start with Windows</summary>
        public static string Tray_AutoStart {
            get { return ResourceManager.GetString("Tray_AutoStart", resourceCulture); }
        }

        /// <summary>Сбросить оверлей / Reset Overlay</summary>
        public static string Tray_ResetOverlay {
            get { return ResourceManager.GetString("Tray_ResetOverlay", resourceCulture); }
        }

        /// <summary>Ошибка имени / Name Error</summary>
        public static string Error_DuplicateNameTitle {
            get { return ResourceManager.GetString("Error_DuplicateNameTitle", resourceCulture); }
        }

        /// <summary>Объект с именем '{0}' уже существует... / An object named '{0}' already exists...</summary>
        public static string Error_DuplicateNameMessage {
            get { return ResourceManager.GetString("Error_DuplicateNameMessage", resourceCulture); }
        }

        /// <summary>ПРИВЯЗКА ПРОЦЕССА / PROCESS BINDING</summary>
        public static string Profile_SectionTitle {
            get { return ResourceManager.GetString("Profile_SectionTitle", resourceCulture); }
        }

        /// <summary>Глобальный (без привязки к процессу) / Global (no process binding)</summary>
        public static string Profile_IsGlobal {
            get { return ResourceManager.GetString("Profile_IsGlobal", resourceCulture); }
        }

        /// <summary>Процесс: / Process:</summary>
        public static string Profile_TargetProcess {
            get { return ResourceManager.GetString("Profile_TargetProcess", resourceCulture); }
        }

        /// <summary>Обновить / Refresh</summary>
        public static string Profile_RefreshProcesses {
            get { return ResourceManager.GetString("Profile_RefreshProcesses", resourceCulture); }
        }

        /// <summary>Только при фокусе окна / Focus required</summary>
        public static string Profile_FocusRequired {
            get { return ResourceManager.GetString("Profile_FocusRequired", resourceCulture); }
        }

        /// <summary>Фильтр заголовка: / Title filter:</summary>
        public static string Profile_WindowTitleFilter {
            get { return ResourceManager.GetString("Profile_WindowTitleFilter", resourceCulture); }
        }

        /// <summary>Отключить макрос / Disable macro</summary>
        public static string Macro_Disable {
            get { return ResourceManager.GetString("Macro_Disable", resourceCulture); }
        }

        /// <summary>Включить макрос / Enable macro</summary>
        public static string Macro_Enable {
            get { return ResourceManager.GetString("Macro_Enable", resourceCulture); }
        }

        /// <summary>Применить изменения / Apply Changes</summary>
        public static string Profile_SaveChanges {
            get { return ResourceManager.GetString("Profile_SaveChanges", resourceCulture); }
        }

        /// <summary>Экспорт / Export</summary>
        public static string Profile_Export {
            get { return ResourceManager.GetString("Profile_Export", resourceCulture); }
        }

        /// <summary>Импорт / Import</summary>
        public static string Profile_Import {
            get { return ResourceManager.GetString("Profile_Import", resourceCulture); }
        }

        /// <summary>Пароль экспорта / Export Password</summary>
        public static string Export_PasswordTitle {
            get { return ResourceManager.GetString("Export_PasswordTitle", resourceCulture); }
        }

        /// <summary>Подсказка для пароля экспорта</summary>
        public static string Export_PasswordPrompt {
            get { return ResourceManager.GetString("Export_PasswordPrompt", resourceCulture); }
        }

        /// <summary>Пароль импорта / Import Password</summary>
        public static string Import_PasswordTitle {
            get { return ResourceManager.GetString("Import_PasswordTitle", resourceCulture); }
        }

        /// <summary>Подсказка для пароля импорта</summary>
        public static string Import_PasswordPrompt {
            get { return ResourceManager.GetString("Import_PasswordPrompt", resourceCulture); }
        }

        /// <summary>Экспорт завершён / Export Complete</summary>
        public static string Export_SuccessTitle {
            get { return ResourceManager.GetString("Export_SuccessTitle", resourceCulture); }
        }

        /// <summary>Профиль успешно экспортирован в {0}</summary>
        public static string Export_SuccessMessage {
            get { return ResourceManager.GetString("Export_SuccessMessage", resourceCulture); }
        }

        /// <summary>Импорт завершён / Import Complete</summary>
        public static string Import_SuccessTitle {
            get { return ResourceManager.GetString("Import_SuccessTitle", resourceCulture); }
        }

        /// <summary>Профиль «{0}» успешно импортирован.</summary>
        public static string Import_SuccessMessage {
            get { return ResourceManager.GetString("Import_SuccessMessage", resourceCulture); }
        }

        /// <summary>Ошибка экспорта / Export Error</summary>
        public static string Error_ExportTitle {
            get { return ResourceManager.GetString("Error_ExportTitle", resourceCulture); }
        }

        /// <summary>Ошибка импорта / Import Error</summary>
        public static string Error_ImportTitle {
            get { return ResourceManager.GetString("Error_ImportTitle", resourceCulture); }
        }

        /// <summary>Неверный пароль / Wrong password</summary>
        public static string Error_WrongPassword {
            get { return ResourceManager.GetString("Error_WrongPassword", resourceCulture); }
        }

        public static string Toolbox_Header            { get { return ResourceManager.GetString("Toolbox_Header",            resourceCulture); } }
        public static string Toolbox_DragHint          { get { return ResourceManager.GetString("Toolbox_DragHint",          resourceCulture); } }
        public static string Toolbox_DelayNode_Name    { get { return ResourceManager.GetString("Toolbox_DelayNode_Name",    resourceCulture); } }
        public static string Toolbox_DelayNode_Desc    { get { return ResourceManager.GetString("Toolbox_DelayNode_Desc",    resourceCulture); } }
        public static string Toolbox_OverlayNode_Name  { get { return ResourceManager.GetString("Toolbox_OverlayNode_Name",  resourceCulture); } }
        public static string Toolbox_OverlayNode_Desc  { get { return ResourceManager.GetString("Toolbox_OverlayNode_Desc",  resourceCulture); } }
        public static string Toolbox_HotkeyNode_Name          { get { return ResourceManager.GetString("Toolbox_HotkeyNode_Name",          resourceCulture); } }
        public static string Toolbox_HotkeyNode_Desc          { get { return ResourceManager.GetString("Toolbox_HotkeyNode_Desc",          resourceCulture); } }
        public static string Toolbox_SpeechTriggerNode_Name   { get { return ResourceManager.GetString("Toolbox_SpeechTriggerNode_Name",   resourceCulture); } }
        public static string Toolbox_SpeechTriggerNode_Desc   { get { return ResourceManager.GetString("Toolbox_SpeechTriggerNode_Desc",   resourceCulture); } }
        public static string Node_SpeechTriggerPhrases        { get { return ResourceManager.GetString("Node_SpeechTriggerPhrases",        resourceCulture); } }
        public static string Node_SpeechTriggerPlaceholder    { get { return ResourceManager.GetString("Node_SpeechTriggerPlaceholder",    resourceCulture); } }
        public static string Toolbox_WebRequestNode_Name      { get { return ResourceManager.GetString("Toolbox_WebRequestNode_Name",      resourceCulture); } }
        public static string Toolbox_WebRequestNode_Desc      { get { return ResourceManager.GetString("Toolbox_WebRequestNode_Desc",      resourceCulture); } }
        public static string Node_WebRequest_Method           { get { return ResourceManager.GetString("Node_WebRequest_Method",           resourceCulture); } }
        public static string Node_WebRequest_Url              { get { return ResourceManager.GetString("Node_WebRequest_Url",              resourceCulture); } }
        public static string Node_WebRequest_Body             { get { return ResourceManager.GetString("Node_WebRequest_Body",             resourceCulture); } }
        public static string Toolbox_SendInputNode_Name { get { return ResourceManager.GetString("Toolbox_SendInputNode_Name", resourceCulture); } }
        public static string Toolbox_SendInputNode_Desc { get { return ResourceManager.GetString("Toolbox_SendInputNode_Desc", resourceCulture); } }

        public static string Tray_RunPause             { get { return ResourceManager.GetString("Tray_RunPause",             resourceCulture); } }

        public static string Explorer_Back             { get { return ResourceManager.GetString("Explorer_Back",             resourceCulture); } }
        public static string Explorer_EmptyTitle       { get { return ResourceManager.GetString("Explorer_EmptyTitle",       resourceCulture); } }
        public static string Explorer_EmptyHint        { get { return ResourceManager.GetString("Explorer_EmptyHint",        resourceCulture); } }
        public static string Explorer_CreateProfile    { get { return ResourceManager.GetString("Explorer_CreateProfile",    resourceCulture); } }
        public static string Explorer_CreateFolder     { get { return ResourceManager.GetString("Explorer_CreateFolder",     resourceCulture); } }
        public static string Explorer_CreateRegion     { get { return ResourceManager.GetString("Explorer_CreateRegion",     resourceCulture); } }
        public static string Explorer_CreateMacro      { get { return ResourceManager.GetString("Explorer_CreateMacro",      resourceCulture); } }
        public static string Explorer_Rename           { get { return ResourceManager.GetString("Explorer_Rename",           resourceCulture); } }
        public static string Explorer_Copy             { get { return ResourceManager.GetString("Explorer_Copy",             resourceCulture); } }
        public static string Explorer_Paste            { get { return ResourceManager.GetString("Explorer_Paste",            resourceCulture); } }
        public static string Explorer_SetPriority      { get { return ResourceManager.GetString("Explorer_SetPriority",      resourceCulture); } }
        public static string Explorer_Delete           { get { return ResourceManager.GetString("Explorer_Delete",           resourceCulture); } }
        public static string Explorer_CtxCreateProfile { get { return ResourceManager.GetString("Explorer_CtxCreateProfile", resourceCulture); } }
        public static string Explorer_CtxCreateFolder  { get { return ResourceManager.GetString("Explorer_CtxCreateFolder",  resourceCulture); } }
        public static string Explorer_CtxCreateRegion  { get { return ResourceManager.GetString("Explorer_CtxCreateRegion",  resourceCulture); } }
        public static string Explorer_CtxCreateMacro    { get { return ResourceManager.GetString("Explorer_CtxCreateMacro",    resourceCulture); } }
        public static string Explorer_CtxEdit            { get { return ResourceManager.GetString("Explorer_CtxEdit",            resourceCulture); } }
        public static string Explorer_CtxDuplicate       { get { return ResourceManager.GetString("Explorer_CtxDuplicate",       resourceCulture); } }
        public static string Explorer_CtxSendToRelease   { get { return ResourceManager.GetString("Explorer_CtxSendToRelease",   resourceCulture); } }
        public static string Explorer_CtxReturnToBeta    { get { return ResourceManager.GetString("Explorer_CtxReturnToBeta",    resourceCulture); } }
        public static string Explorer_CtxCreateSubFolder { get { return ResourceManager.GetString("Explorer_CtxCreateSubFolder", resourceCulture); } }
        public static string Explorer_CtxCreateMacroHere { get { return ResourceManager.GetString("Explorer_CtxCreateMacroHere", resourceCulture); } }

        public static string Node_DelayMs              { get { return ResourceManager.GetString("Node_DelayMs",              resourceCulture); } }
        public static string Node_OverlayText          { get { return ResourceManager.GetString("Node_OverlayText",          resourceCulture); } }
        public static string Node_DurationMs           { get { return ResourceManager.GetString("Node_DurationMs",           resourceCulture); } }
        public static string Node_HotkeyHint           { get { return ResourceManager.GetString("Node_HotkeyHint",           resourceCulture); } }
        public static string Node_KeyLabel             { get { return ResourceManager.GetString("Node_KeyLabel",             resourceCulture); } }
        public static string Node_KeyInputHint         { get { return ResourceManager.GetString("Node_KeyInputHint",         resourceCulture); } }
        public static string Node_ModifiersLabel       { get { return ResourceManager.GetString("Node_ModifiersLabel",       resourceCulture); } }
        public static string Node_DelayAfterMs           { get { return ResourceManager.GetString("Node_DelayAfterMs",           resourceCulture); } }
        public static string Node_DelayRandom            { get { return ResourceManager.GetString("Node_DelayRandom",            resourceCulture); } }
        public static string Node_DelayMin               { get { return ResourceManager.GetString("Node_DelayMin",               resourceCulture); } }
        public static string Node_DelayMax               { get { return ResourceManager.GetString("Node_DelayMax",               resourceCulture); } }
        public static string Node_SendInput_RandomDelay  { get { return ResourceManager.GetString("Node_SendInput_RandomDelay",  resourceCulture); } }
        public static string Node_SendInput_MinDelay     { get { return ResourceManager.GetString("Node_SendInput_MinDelay",     resourceCulture); } }
        public static string Node_SendInput_MaxDelay     { get { return ResourceManager.GetString("Node_SendInput_MaxDelay",     resourceCulture); } }
        public static string Node_KeyTooltip             { get { return ResourceManager.GetString("Node_KeyTooltip",             resourceCulture); } }

        public static string Blueprint_ToolboxToggle   { get { return ResourceManager.GetString("Blueprint_ToolboxToggle",   resourceCulture); } }
        public static string Blueprint_PropsToggle     { get { return ResourceManager.GetString("Blueprint_PropsToggle",     resourceCulture); } }
        public static string Blueprint_PropsHeader     { get { return ResourceManager.GetString("Blueprint_PropsHeader",     resourceCulture); } }
        public static string Blueprint_PropsEmpty      { get { return ResourceManager.GetString("Blueprint_PropsEmpty",      resourceCulture); } }
        public static string Blueprint_HotkeyLabel     { get { return ResourceManager.GetString("Blueprint_HotkeyLabel",     resourceCulture); } }
        public static string Blueprint_NodeCtxSetStart { get { return ResourceManager.GetString("Blueprint_NodeCtxSetStart", resourceCulture); } }
        public static string Blueprint_NodeCtxDelete   { get { return ResourceManager.GetString("Blueprint_NodeCtxDelete",   resourceCulture); } }
        public static string Blueprint_ConnectionDelete { get { return ResourceManager.GetString("Blueprint_ConnectionDelete", resourceCulture); } }

        public static string Nav_Macros                { get { return ResourceManager.GetString("Nav_Macros",                resourceCulture); } }
        public static string Nav_Blueprint             { get { return ResourceManager.GetString("Nav_Blueprint",             resourceCulture); } }
        public static string Nav_Queue                 { get { return ResourceManager.GetString("Nav_Queue",                 resourceCulture); } }
        public static string Nav_Network               { get { return ResourceManager.GetString("Nav_Network",               resourceCulture); } }
        public static string Nav_Logs                  { get { return ResourceManager.GetString("Nav_Logs",                  resourceCulture); } }
        public static string Dashboard_Close           { get { return ResourceManager.GetString("Dashboard_Close",           resourceCulture); } }

        public static string Logs_Title                { get { return ResourceManager.GetString("Logs_Title",                resourceCulture); } }
        public static string Logs_Refresh              { get { return ResourceManager.GetString("Logs_Refresh",              resourceCulture); } }
        public static string Logs_NoEntries            { get { return ResourceManager.GetString("Logs_NoEntries",            resourceCulture); } }
        public static string Logs_ReadError            { get { return ResourceManager.GetString("Logs_ReadError",            resourceCulture); } }
        public static string Logs_SearchPlaceholder    { get { return ResourceManager.GetString("Logs_SearchPlaceholder",    resourceCulture); } }

        public static string Blueprint_PortIn          { get { return ResourceManager.GetString("Blueprint_PortIn",          resourceCulture); } }
        public static string Blueprint_PortSuccess     { get { return ResourceManager.GetString("Blueprint_PortSuccess",     resourceCulture); } }
        public static string Blueprint_PortError       { get { return ResourceManager.GetString("Blueprint_PortError",       resourceCulture); } }
        public static string Blueprint_PortData        { get { return ResourceManager.GetString("Blueprint_PortData",        resourceCulture); } }
        public static string Tray_RunPlay              { get { return ResourceManager.GetString("Tray_RunPlay",              resourceCulture); } }

        public static string Net_Header                { get { return ResourceManager.GetString("Net_Header",                resourceCulture); } }
        public static string Net_ServerUrl             { get { return ResourceManager.GetString("Net_ServerUrl",             resourceCulture); } }
        public static string Net_Connected             { get { return ResourceManager.GetString("Net_Connected",             resourceCulture); } }
        public static string Net_Disconnected          { get { return ResourceManager.GetString("Net_Disconnected",          resourceCulture); } }
        public static string Net_Reconnect                    { get { return ResourceManager.GetString("Net_Reconnect",                    resourceCulture); } }

        public static string Toolbox_Category_SystemAndInput  { get { return ResourceManager.GetString("Toolbox_Category_SystemAndInput",  resourceCulture); } }
        public static string Toolbox_Category_UserInterface   { get { return ResourceManager.GetString("Toolbox_Category_UserInterface",   resourceCulture); } }
        public static string Toolbox_Category_NetworkAndApi   { get { return ResourceManager.GetString("Toolbox_Category_NetworkAndApi",   resourceCulture); } }
        public static string Toolbox_Category_VisionAndAi    { get { return ResourceManager.GetString("Toolbox_Category_VisionAndAi",    resourceCulture); } }
        public static string Toolbox_Category_OBS            { get { return ResourceManager.GetString("Toolbox_Category_OBS",            resourceCulture); } }

        public static string Nav_AiAndNetwork          { get { return ResourceManager.GetString("Nav_AiAndNetwork",          resourceCulture); } }
        public static string AiSettings_SpeechSection  { get { return ResourceManager.GetString("AiSettings_SpeechSection",  resourceCulture); } }
        public static string AiSettings_LlmSection     { get { return ResourceManager.GetString("AiSettings_LlmSection",     resourceCulture); } }
        public static string AiSettings_NetworkSection { get { return ResourceManager.GetString("AiSettings_NetworkSection", resourceCulture); } }
        public static string AiSettings_Microphone     { get { return ResourceManager.GetString("AiSettings_Microphone",     resourceCulture); } }
        public static string AiSettings_RefreshMics    { get { return ResourceManager.GetString("AiSettings_RefreshMics",    resourceCulture); } }
        public static string AiSettings_Engine         { get { return ResourceManager.GetString("AiSettings_Engine",         resourceCulture); } }
        public static string AiSettings_Language       { get { return ResourceManager.GetString("AiSettings_Language",       resourceCulture); } }
        public static string AiSettings_WhisperModel   { get { return ResourceManager.GetString("AiSettings_WhisperModel",   resourceCulture); } }
        public static string AiSettings_ModelBase      { get { return ResourceManager.GetString("AiSettings_ModelBase",      resourceCulture); } }
        public static string AiSettings_ModelTurbo     { get { return ResourceManager.GetString("AiSettings_ModelTurbo",     resourceCulture); } }
        public static string AiSettings_Sensitivity    { get { return ResourceManager.GetString("AiSettings_Sensitivity",    resourceCulture); } }
        public static string AiSettings_SpeechEnabled       { get { return ResourceManager.GetString("AiSettings_SpeechEnabled",       resourceCulture); } }
        public static string AiSettings_ActivationNames     { get { return ResourceManager.GetString("AiSettings_ActivationNames",     resourceCulture); } }
        public static string AiSettings_ActivationNamesHint { get { return ResourceManager.GetString("AiSettings_ActivationNamesHint", resourceCulture); } }
        public static string AiSettings_ModelStatus         { get { return ResourceManager.GetString("AiSettings_ModelStatus",         resourceCulture); } }
        public static string AiSettings_OllamaUrl      { get { return ResourceManager.GetString("AiSettings_OllamaUrl",      resourceCulture); } }
        public static string AiSettings_OllamaModel    { get { return ResourceManager.GetString("AiSettings_OllamaModel",    resourceCulture); } }
        public static string AiSettings_SaveSettings   { get { return ResourceManager.GetString("AiSettings_SaveSettings",   resourceCulture); } }
        public static string AiSettings_StatusLoaded   { get { return ResourceManager.GetString("AiSettings_StatusLoaded",   resourceCulture); } }
        public static string AiSettings_StatusNotLoaded{ get { return ResourceManager.GetString("AiSettings_StatusNotLoaded",resourceCulture); } }

        public static string AiSettings_ResetSession { get { return ResourceManager.GetString("AiSettings_ResetSession", resourceCulture); } }

        public static string AiSettings_ProactiveMode { get { return ResourceManager.GetString("AiSettings_ProactiveMode", resourceCulture); } }

        public static string AiSettings_ProactiveInterval { get { return ResourceManager.GetString("AiSettings_ProactiveInterval", resourceCulture); } }

        public static string Tray_ResetAiSession { get { return ResourceManager.GetString("Tray_ResetAiSession", resourceCulture); } }

        public static string AiSettings_OllamaOffline { get { return ResourceManager.GetString("AiSettings_OllamaOffline", resourceCulture); } }

        public static string AiSettings_RefreshModels { get { return ResourceManager.GetString("AiSettings_RefreshModels", resourceCulture); } }

        public static string Toolbox_MouseActionNode_Name { get { return ResourceManager.GetString("Toolbox_MouseActionNode_Name", resourceCulture); } }
        public static string Toolbox_MouseActionNode_Desc { get { return ResourceManager.GetString("Toolbox_MouseActionNode_Desc", resourceCulture); } }
        public static string Toolbox_RunProcessNode_Name  { get { return ResourceManager.GetString("Toolbox_RunProcessNode_Name",  resourceCulture); } }
        public static string Toolbox_RunProcessNode_Desc  { get { return ResourceManager.GetString("Toolbox_RunProcessNode_Desc",  resourceCulture); } }
        public static string Node_MouseActionType         { get { return ResourceManager.GetString("Node_MouseActionType",         resourceCulture); } }
        public static string Node_MouseX                  { get { return ResourceManager.GetString("Node_MouseX",                  resourceCulture); } }
        public static string Node_MouseY                  { get { return ResourceManager.GetString("Node_MouseY",                  resourceCulture); } }
        public static string Node_ScrollAmount            { get { return ResourceManager.GetString("Node_ScrollAmount",            resourceCulture); } }
        public static string Node_ActiveProcessLabel       { get { return ResourceManager.GetString("Node_ActiveProcessLabel",       resourceCulture); } }
        public static string Node_FilePathOrUrl           { get { return ResourceManager.GetString("Node_FilePathOrUrl",           resourceCulture); } }
        public static string Node_Arguments               { get { return ResourceManager.GetString("Node_Arguments",               resourceCulture); } }

        public static string AiSettings_AiEnabled         { get { return ResourceManager.GetString("AiSettings_AiEnabled",         resourceCulture); } }
        public static string AiSettings_CharacterBtn      { get { return ResourceManager.GetString("AiSettings_CharacterBtn",      resourceCulture); } }
        public static string AiCharacter_Title            { get { return ResourceManager.GetString("AiCharacter_Title",            resourceCulture); } }
        public static string AiCharacter_NameLabel        { get { return ResourceManager.GetString("AiCharacter_NameLabel",        resourceCulture); } }
        public static string AiCharacter_PromptLabel      { get { return ResourceManager.GetString("AiCharacter_PromptLabel",      resourceCulture); } }
        public static string AiCharacter_Apply            { get { return ResourceManager.GetString("AiCharacter_Apply",            resourceCulture); } }
        public static string AiCharacter_Cancel           { get { return ResourceManager.GetString("AiCharacter_Cancel",           resourceCulture); } }
        public static string Tray_AiEnabled               { get { return ResourceManager.GetString("Tray_AiEnabled",               resourceCulture); } }

        public static string Toolbox_ClipboardNode_Name      { get { return ResourceManager.GetString("Toolbox_ClipboardNode_Name",      resourceCulture); } }
        public static string Toolbox_ClipboardNode_Desc      { get { return ResourceManager.GetString("Toolbox_ClipboardNode_Desc",      resourceCulture); } }
        public static string Toolbox_TextConditionNode_Name  { get { return ResourceManager.GetString("Toolbox_TextConditionNode_Name",  resourceCulture); } }
        public static string Toolbox_TextConditionNode_Desc  { get { return ResourceManager.GetString("Toolbox_TextConditionNode_Desc",  resourceCulture); } }
        public static string Node_ClipboardDataType          { get { return ResourceManager.GetString("Node_ClipboardDataType",          resourceCulture); } }
        public static string Node_ClipboardAction            { get { return ResourceManager.GetString("Node_ClipboardAction",            resourceCulture); } }
        public static string Node_ClipboardTextToWrite       { get { return ResourceManager.GetString("Node_ClipboardTextToWrite",       resourceCulture); } }
        public static string Node_TextCompareType            { get { return ResourceManager.GetString("Node_TextCompareType",            resourceCulture); } }
        public static string Node_TextMatchValue             { get { return ResourceManager.GetString("Node_TextMatchValue",             resourceCulture); } }
        public static string Node_TextIgnoreCase             { get { return ResourceManager.GetString("Node_TextIgnoreCase",             resourceCulture); } }

        public static string AiSettings_TtsSection  { get { return ResourceManager.GetString("AiSettings_TtsSection",  resourceCulture); } }
        public static string AiSettings_TtsEnabled  { get { return ResourceManager.GetString("AiSettings_TtsEnabled",  resourceCulture); } }
        public static string AiSettings_ShowSubtitles { get { return ResourceManager.GetString("AiSettings_ShowSubtitles", resourceCulture); } }
        public static string AiSettings_TtsMode       { get { return ResourceManager.GetString("AiSettings_TtsMode",       resourceCulture); } }
        public static string AiSettings_TtsVoice    { get { return ResourceManager.GetString("AiSettings_TtsVoice",    resourceCulture); } }
        public static string AiSettings_TtsSpeed    { get { return ResourceManager.GetString("AiSettings_TtsSpeed",    resourceCulture); } }
        public static string AiSettings_TtsVolume   { get { return ResourceManager.GetString("AiSettings_TtsVolume",   resourceCulture); } }
        public static string AiSettings_TtsPreview  { get { return ResourceManager.GetString("AiSettings_TtsPreview",  resourceCulture); } }
        public static string AiSettings_TtsNoVoices { get { return ResourceManager.GetString("AiSettings_TtsNoVoices", resourceCulture); } }

        public static string Toolbox_ObsSetSceneNode_Name      { get { return ResourceManager.GetString("Toolbox_ObsSetSceneNode_Name",      resourceCulture); } }
        public static string Toolbox_ObsSetSceneNode_Desc      { get { return ResourceManager.GetString("Toolbox_ObsSetSceneNode_Desc",      resourceCulture); } }
        public static string Toolbox_ObsToggleMuteNode_Name    { get { return ResourceManager.GetString("Toolbox_ObsToggleMuteNode_Name",    resourceCulture); } }
        public static string Toolbox_ObsToggleMuteNode_Desc    { get { return ResourceManager.GetString("Toolbox_ObsToggleMuteNode_Desc",    resourceCulture); } }
        public static string Toolbox_ObsRecordControlNode_Name { get { return ResourceManager.GetString("Toolbox_ObsRecordControlNode_Name", resourceCulture); } }
        public static string Toolbox_ObsRecordControlNode_Desc { get { return ResourceManager.GetString("Toolbox_ObsRecordControlNode_Desc", resourceCulture); } }
        public static string Node_ObsSceneName                 { get { return ResourceManager.GetString("Node_ObsSceneName",                 resourceCulture); } }
        public static string Node_ObsSceneMode                 { get { return ResourceManager.GetString("Node_ObsSceneMode",                 resourceCulture); } }
        public static string Node_ObsDisconnectedHint          { get { return ResourceManager.GetString("Node_ObsDisconnectedHint",          resourceCulture); } }
        public static string Node_ObsInputName                 { get { return ResourceManager.GetString("Node_ObsInputName",                 resourceCulture); } }
        public static string Node_ObsMute                      { get { return ResourceManager.GetString("Node_ObsMute",                      resourceCulture); } }
        public static string Node_ObsRecordAction              { get { return ResourceManager.GetString("Node_ObsRecordAction",              resourceCulture); } }

        public static string Toolbox_ObsSceneManagerNode_Name             { get { return ResourceManager.GetString("Toolbox_ObsSceneManagerNode_Name",             resourceCulture); } }
        public static string Toolbox_ObsSceneManagerNode_Desc             { get { return ResourceManager.GetString("Toolbox_ObsSceneManagerNode_Desc",             resourceCulture); } }
        public static string Toolbox_ObsSourceVisibilityManagerNode_Name  { get { return ResourceManager.GetString("Toolbox_ObsSourceVisibilityManagerNode_Name",  resourceCulture); } }
        public static string Toolbox_ObsSourceVisibilityManagerNode_Desc  { get { return ResourceManager.GetString("Toolbox_ObsSourceVisibilityManagerNode_Desc",  resourceCulture); } }
        public static string Toolbox_ObsAudioManagerNode_Name             { get { return ResourceManager.GetString("Toolbox_ObsAudioManagerNode_Name",             resourceCulture); } }
        public static string Toolbox_ObsAudioManagerNode_Desc             { get { return ResourceManager.GetString("Toolbox_ObsAudioManagerNode_Desc",             resourceCulture); } }
        public static string Toolbox_ObsStreamAndRecordManagerNode_Name   { get { return ResourceManager.GetString("Toolbox_ObsStreamAndRecordManagerNode_Name",   resourceCulture); } }
        public static string Toolbox_ObsStreamAndRecordManagerNode_Desc   { get { return ResourceManager.GetString("Toolbox_ObsStreamAndRecordManagerNode_Desc",   resourceCulture); } }
        public static string Toolbox_ObsDynamicContentManagerNode_Name    { get { return ResourceManager.GetString("Toolbox_ObsDynamicContentManagerNode_Name",    resourceCulture); } }
        public static string Toolbox_ObsDynamicContentManagerNode_Desc    { get { return ResourceManager.GetString("Toolbox_ObsDynamicContentManagerNode_Desc",    resourceCulture); } }

        public static string Node_ObsSourceScene      { get { return ResourceManager.GetString("Node_ObsSourceScene",      resourceCulture); } }
        public static string Node_ObsSource           { get { return ResourceManager.GetString("Node_ObsSource",           resourceCulture); } }
        public static string Node_ObsFilter           { get { return ResourceManager.GetString("Node_ObsFilter",           resourceCulture); } }
        public static string Node_ObsTargetType       { get { return ResourceManager.GetString("Node_ObsTargetType",       resourceCulture); } }
        public static string Node_ObsVisibilityAction { get { return ResourceManager.GetString("Node_ObsVisibilityAction", resourceCulture); } }
        public static string Node_ObsAudioAction      { get { return ResourceManager.GetString("Node_ObsAudioAction",      resourceCulture); } }
        public static string Node_ObsTargetVolumeDb   { get { return ResourceManager.GetString("Node_ObsTargetVolumeDb",   resourceCulture); } }
        public static string Node_ObsStreamTarget     { get { return ResourceManager.GetString("Node_ObsStreamTarget",     resourceCulture); } }
        public static string Node_ObsStreamAction     { get { return ResourceManager.GetString("Node_ObsStreamAction",     resourceCulture); } }
        public static string Node_ObsContentType      { get { return ResourceManager.GetString("Node_ObsContentType",      resourceCulture); } }
        public static string Node_ObsTextContent      { get { return ResourceManager.GetString("Node_ObsTextContent",      resourceCulture); } }
        public static string Node_ObsFilePath         { get { return ResourceManager.GetString("Node_ObsFilePath",         resourceCulture); } }
        public static string Node_ObsMediaAction      { get { return ResourceManager.GetString("Node_ObsMediaAction",      resourceCulture); } }
        public static string Node_ObsAudioInput       { get { return ResourceManager.GetString("Node_ObsAudioInput",       resourceCulture); } }

        public static string Enum_ClipboardActionType_CopyActiveText { get { return ResourceManager.GetString("Enum_ClipboardActionType_CopyActiveText", resourceCulture); } }
        public static string Enum_ClipboardActionType_WriteText      { get { return ResourceManager.GetString("Enum_ClipboardActionType_WriteText",      resourceCulture); } }
        public static string Enum_ClipboardActionType_ReadText       { get { return ResourceManager.GetString("Enum_ClipboardActionType_ReadText",       resourceCulture); } }

        public static string Enum_ClipboardDataType_Text             { get { return ResourceManager.GetString("Enum_ClipboardDataType_Text",             resourceCulture); } }
        public static string Enum_ClipboardDataType_Image            { get { return ResourceManager.GetString("Enum_ClipboardDataType_Image",            resourceCulture); } }
        public static string Enum_ClipboardImageAction_WriteImage    { get { return ResourceManager.GetString("Enum_ClipboardImageAction_WriteImage",    resourceCulture); } }
        public static string Enum_ClipboardImageAction_ReadImage     { get { return ResourceManager.GetString("Enum_ClipboardImageAction_ReadImage",     resourceCulture); } }
        public static string Enum_ClipboardImageAction_Clear         { get { return ResourceManager.GetString("Enum_ClipboardImageAction_Clear",         resourceCulture); } }

        public static string Enum_MouseActionType_LeftClick       { get { return ResourceManager.GetString("Enum_MouseActionType_LeftClick",       resourceCulture); } }
        public static string Enum_MouseActionType_RightClick      { get { return ResourceManager.GetString("Enum_MouseActionType_RightClick",      resourceCulture); } }
        public static string Enum_MouseActionType_DoubleLeftClick  { get { return ResourceManager.GetString("Enum_MouseActionType_DoubleLeftClick",  resourceCulture); } }
        public static string Enum_MouseActionType_Move             { get { return ResourceManager.GetString("Enum_MouseActionType_Move",             resourceCulture); } }
        public static string Enum_MouseActionType_Scroll           { get { return ResourceManager.GetString("Enum_MouseActionType_Scroll",           resourceCulture); } }
        public static string Enum_MouseActionType_LeftButtonDown   { get { return ResourceManager.GetString("Enum_MouseActionType_LeftButtonDown",   resourceCulture); } }
        public static string Enum_MouseActionType_LeftButtonUp     { get { return ResourceManager.GetString("Enum_MouseActionType_LeftButtonUp",     resourceCulture); } }

        public static string Enum_TextCompareType_Contains    { get { return ResourceManager.GetString("Enum_TextCompareType_Contains",    resourceCulture); } }
        public static string Enum_TextCompareType_Equals      { get { return ResourceManager.GetString("Enum_TextCompareType_Equals",      resourceCulture); } }
        public static string Enum_TextCompareType_StartsWith  { get { return ResourceManager.GetString("Enum_TextCompareType_StartsWith",  resourceCulture); } }
        public static string Enum_TextCompareType_IsEmpty              { get { return ResourceManager.GetString("Enum_TextCompareType_IsEmpty",              resourceCulture); } }
        public static string Enum_TextCompareType_ContainsWholeWord    { get { return ResourceManager.GetString("Enum_TextCompareType_ContainsWholeWord",    resourceCulture); } }
        public static string Enum_TextCompareType_GreaterThanOrEqual   { get { return ResourceManager.GetString("Enum_TextCompareType_GreaterThanOrEqual",   resourceCulture); } }
        public static string Enum_TextCompareType_LessThanOrEqual    { get { return ResourceManager.GetString("Enum_TextCompareType_LessThanOrEqual",    resourceCulture); } }
        public static string Enum_TextCompareType_Between            { get { return ResourceManager.GetString("Enum_TextCompareType_Between",            resourceCulture); } }
        public static string Node_TextCondition_Min                  { get { return ResourceManager.GetString("Node_TextCondition_Min",                  resourceCulture); } }
        public static string Node_TextCondition_Max                  { get { return ResourceManager.GetString("Node_TextCondition_Max",                  resourceCulture); } }

        public static string Enum_WinProcessAction_Kill          { get { return ResourceManager.GetString("Enum_WinProcessAction_Kill",          resourceCulture); } }
        public static string Enum_WinProcessAction_CheckRunning  { get { return ResourceManager.GetString("Enum_WinProcessAction_CheckRunning",  resourceCulture); } }
        public static string Enum_WinProcessAction_Restart       { get { return ResourceManager.GetString("Enum_WinProcessAction_Restart",       resourceCulture); } }

        public static string Enum_WinWindowAction_Minimize      { get { return ResourceManager.GetString("Enum_WinWindowAction_Minimize",      resourceCulture); } }
        public static string Enum_WinWindowAction_Maximize      { get { return ResourceManager.GetString("Enum_WinWindowAction_Maximize",      resourceCulture); } }
        public static string Enum_WinWindowAction_Restore       { get { return ResourceManager.GetString("Enum_WinWindowAction_Restore",       resourceCulture); } }
        public static string Enum_WinWindowAction_Close         { get { return ResourceManager.GetString("Enum_WinWindowAction_Close",         resourceCulture); } }
        public static string Enum_WinWindowAction_MoveAndResize { get { return ResourceManager.GetString("Enum_WinWindowAction_MoveAndResize", resourceCulture); } }
        public static string Enum_WinWindowAction_CheckActive   { get { return ResourceManager.GetString("Enum_WinWindowAction_CheckActive",   resourceCulture); } }
        public static string Enum_WinWindowAction_MinimizeAll   { get { return ResourceManager.GetString("Enum_WinWindowAction_MinimizeAll",   resourceCulture); } }
        public static string Enum_WinWindowAction_RestoreAll    { get { return ResourceManager.GetString("Enum_WinWindowAction_RestoreAll",    resourceCulture); } }
        public static string Enum_WinWindowAction_TileVertical  { get { return ResourceManager.GetString("Enum_WinWindowAction_TileVertical",  resourceCulture); } }
        public static string Enum_WinWindowAction_TileHorizontal{ get { return ResourceManager.GetString("Enum_WinWindowAction_TileHorizontal",resourceCulture); } }
        public static string Enum_WinWindowAction_Cascade       { get { return ResourceManager.GetString("Enum_WinWindowAction_Cascade",       resourceCulture); } }
        public static string Enum_WinWindowAction_Focus         { get { return ResourceManager.GetString("Enum_WinWindowAction_Focus",         resourceCulture); } }

        public static string Enum_ObsSceneMode_Switch           { get { return ResourceManager.GetString("Enum_ObsSceneMode_Switch",           resourceCulture); } }
        public static string Enum_ObsSceneMode_CheckActive      { get { return ResourceManager.GetString("Enum_ObsSceneMode_CheckActive",      resourceCulture); } }
        public static string Enum_ObsVisibilityTarget_Source    { get { return ResourceManager.GetString("Enum_ObsVisibilityTarget_Source",    resourceCulture); } }
        public static string Enum_ObsVisibilityTarget_Filter    { get { return ResourceManager.GetString("Enum_ObsVisibilityTarget_Filter",    resourceCulture); } }
        public static string Enum_ObsVisibilityAction_Show      { get { return ResourceManager.GetString("Enum_ObsVisibilityAction_Show",      resourceCulture); } }
        public static string Enum_ObsVisibilityAction_Hide      { get { return ResourceManager.GetString("Enum_ObsVisibilityAction_Hide",      resourceCulture); } }
        public static string Enum_ObsVisibilityAction_Toggle    { get { return ResourceManager.GetString("Enum_ObsVisibilityAction_Toggle",    resourceCulture); } }
        public static string Enum_ObsAudioAction_Mute           { get { return ResourceManager.GetString("Enum_ObsAudioAction_Mute",           resourceCulture); } }
        public static string Enum_ObsAudioAction_Unmute         { get { return ResourceManager.GetString("Enum_ObsAudioAction_Unmute",         resourceCulture); } }
        public static string Enum_ObsAudioAction_ToggleMute     { get { return ResourceManager.GetString("Enum_ObsAudioAction_ToggleMute",     resourceCulture); } }
        public static string Enum_ObsAudioAction_SetVolume      { get { return ResourceManager.GetString("Enum_ObsAudioAction_SetVolume",      resourceCulture); } }
        public static string Enum_ObsStreamTarget_Recording     { get { return ResourceManager.GetString("Enum_ObsStreamTarget_Recording",     resourceCulture); } }
        public static string Enum_ObsStreamTarget_Streaming     { get { return ResourceManager.GetString("Enum_ObsStreamTarget_Streaming",     resourceCulture); } }
        public static string Enum_ObsStreamTarget_ReplayBuffer  { get { return ResourceManager.GetString("Enum_ObsStreamTarget_ReplayBuffer",  resourceCulture); } }
        public static string Enum_ObsStreamAction_Start         { get { return ResourceManager.GetString("Enum_ObsStreamAction_Start",         resourceCulture); } }
        public static string Enum_ObsStreamAction_Stop          { get { return ResourceManager.GetString("Enum_ObsStreamAction_Stop",          resourceCulture); } }
        public static string Enum_ObsStreamAction_Toggle        { get { return ResourceManager.GetString("Enum_ObsStreamAction_Toggle",        resourceCulture); } }
        public static string Enum_ObsStreamAction_Save          { get { return ResourceManager.GetString("Enum_ObsStreamAction_Save",          resourceCulture); } }
        public static string Enum_ObsContentType_Text           { get { return ResourceManager.GetString("Enum_ObsContentType_Text",           resourceCulture); } }
        public static string Enum_ObsContentType_Image          { get { return ResourceManager.GetString("Enum_ObsContentType_Image",          resourceCulture); } }
        public static string Enum_ObsContentType_Media          { get { return ResourceManager.GetString("Enum_ObsContentType_Media",          resourceCulture); } }
        public static string Enum_ObsMediaAction_Play           { get { return ResourceManager.GetString("Enum_ObsMediaAction_Play",           resourceCulture); } }
        public static string Enum_ObsMediaAction_Pause          { get { return ResourceManager.GetString("Enum_ObsMediaAction_Pause",          resourceCulture); } }
        public static string Enum_ObsMediaAction_Stop           { get { return ResourceManager.GetString("Enum_ObsMediaAction_Stop",           resourceCulture); } }
        public static string Enum_ObsMediaAction_Restart        { get { return ResourceManager.GetString("Enum_ObsMediaAction_Restart",        resourceCulture); } }
        public static string Enum_ObsVisibilityAction_Enable    { get { return ResourceManager.GetString("Enum_ObsVisibilityAction_Enable",    resourceCulture); } }
        public static string Enum_ObsVisibilityAction_Disable   { get { return ResourceManager.GetString("Enum_ObsVisibilityAction_Disable",   resourceCulture); } }
        public static string Enum_ObsAudioAction_CheckMute      { get { return ResourceManager.GetString("Enum_ObsAudioAction_CheckMute",      resourceCulture); } }
        public static string Enum_ObsAudioAction_CheckVolume    { get { return ResourceManager.GetString("Enum_ObsAudioAction_CheckVolume",    resourceCulture); } }
        public static string Enum_ObsStreamTarget_Stream        { get { return ResourceManager.GetString("Enum_ObsStreamTarget_Stream",        resourceCulture); } }
        public static string Enum_ObsStreamTarget_Record        { get { return ResourceManager.GetString("Enum_ObsStreamTarget_Record",        resourceCulture); } }
        public static string Enum_ObsStreamAction_Pause         { get { return ResourceManager.GetString("Enum_ObsStreamAction_Pause",         resourceCulture); } }
        public static string Enum_ObsStreamAction_Resume        { get { return ResourceManager.GetString("Enum_ObsStreamAction_Resume",        resourceCulture); } }
        public static string Enum_ObsStreamAction_Check         { get { return ResourceManager.GetString("Enum_ObsStreamAction_Check",         resourceCulture); } }

        public static string Toolbox_Category_WindowsSystem     { get { return ResourceManager.GetString("Toolbox_Category_WindowsSystem",     resourceCulture); } }
        public static string Toolbox_Category_ScriptsAndData    { get { return ResourceManager.GetString("Toolbox_Category_ScriptsAndData",    resourceCulture); } }
        public static string Toolbox_Category_SmartLogic        { get { return ResourceManager.GetString("Toolbox_Category_SmartLogic",        resourceCulture); } }

        public static string Toolbox_WinProcessManagerNode_Name { get { return ResourceManager.GetString("Toolbox_WinProcessManagerNode_Name", resourceCulture); } }
        public static string Toolbox_WinProcessManagerNode_Desc { get { return ResourceManager.GetString("Toolbox_WinProcessManagerNode_Desc", resourceCulture); } }
        public static string Toolbox_WinWindowManagerNode_Name  { get { return ResourceManager.GetString("Toolbox_WinWindowManagerNode_Name",  resourceCulture); } }
        public static string Toolbox_WinWindowManagerNode_Desc  { get { return ResourceManager.GetString("Toolbox_WinWindowManagerNode_Desc",  resourceCulture); } }
        public static string Toolbox_WinSystemPowerNode_Name    { get { return ResourceManager.GetString("Toolbox_WinSystemPowerNode_Name",    resourceCulture); } }
        public static string Toolbox_WinSystemPowerNode_Desc    { get { return ResourceManager.GetString("Toolbox_WinSystemPowerNode_Desc",    resourceCulture); } }
        public static string Toolbox_WinPowerShellNode_Name     { get { return ResourceManager.GetString("Toolbox_WinPowerShellNode_Name",     resourceCulture); } }
        public static string Toolbox_WinPowerShellNode_Desc     { get { return ResourceManager.GetString("Toolbox_WinPowerShellNode_Desc",     resourceCulture); } }
        public static string Toolbox_WinAudioDeviceNode_Name    { get { return ResourceManager.GetString("Toolbox_WinAudioDeviceNode_Name",    resourceCulture); } }
        public static string Toolbox_WinAudioDeviceNode_Desc    { get { return ResourceManager.GetString("Toolbox_WinAudioDeviceNode_Desc",    resourceCulture); } }
        public static string Toolbox_WaitSmartDelayNode_Name    { get { return ResourceManager.GetString("Toolbox_WaitSmartDelayNode_Name",    resourceCulture); } }
        public static string Toolbox_WaitSmartDelayNode_Desc    { get { return ResourceManager.GetString("Toolbox_WaitSmartDelayNode_Desc",    resourceCulture); } }
        public static string Toolbox_WaitRandomDelayNode_Name   { get { return ResourceManager.GetString("Toolbox_WaitRandomDelayNode_Name",   resourceCulture); } }
        public static string Toolbox_WaitRandomDelayNode_Desc   { get { return ResourceManager.GetString("Toolbox_WaitRandomDelayNode_Desc",   resourceCulture); } }
        public static string Toolbox_LogicCounterNode_Name      { get { return ResourceManager.GetString("Toolbox_LogicCounterNode_Name",      resourceCulture); } }
        public static string Toolbox_LogicCounterNode_Desc      { get { return ResourceManager.GetString("Toolbox_LogicCounterNode_Desc",      resourceCulture); } }
        public static string Toolbox_WinSpeakTextNode_Name      { get { return ResourceManager.GetString("Toolbox_WinSpeakTextNode_Name",      resourceCulture); } }
        public static string Toolbox_WinSpeakTextNode_Desc      { get { return ResourceManager.GetString("Toolbox_WinSpeakTextNode_Desc",      resourceCulture); } }
        public static string Node_SpeakText                     { get { return ResourceManager.GetString("Node_SpeakText",                     resourceCulture); } }
        public static string Node_SpeakVoice                    { get { return ResourceManager.GetString("Node_SpeakVoice",                    resourceCulture); } }
        public static string Node_SpeakTtsDisabledHint          { get { return ResourceManager.GetString("Node_SpeakTtsDisabledHint",          resourceCulture); } }
        public static string Enum_WinPowerAction_Sleep          { get { return ResourceManager.GetString("Enum_WinPowerAction_Sleep",          resourceCulture); } }
        public static string Enum_WinPowerAction_Shutdown       { get { return ResourceManager.GetString("Enum_WinPowerAction_Shutdown",       resourceCulture); } }
        public static string Enum_WinPowerAction_Restart        { get { return ResourceManager.GetString("Enum_WinPowerAction_Restart",        resourceCulture); } }
        public static string Enum_WinPowerAction_Lock           { get { return ResourceManager.GetString("Enum_WinPowerAction_Lock",           resourceCulture); } }
        public static string Enum_WinPowerAction_MonitorOff     { get { return ResourceManager.GetString("Enum_WinPowerAction_MonitorOff",     resourceCulture); } }
        public static string Node_Power_Action                  { get { return ResourceManager.GetString("Node_Power_Action",                  resourceCulture); } }
        public static string Node_PowerShell_Script             { get { return ResourceManager.GetString("Node_PowerShell_Script",             resourceCulture); } }
        public static string Node_PowerShell_UsePwsh            { get { return ResourceManager.GetString("Node_PowerShell_UsePwsh",            resourceCulture); } }
        public static string Enum_SmartWaitType_UntilWindowActive { get { return ResourceManager.GetString("Enum_SmartWaitType_UntilWindowActive", resourceCulture); } }
        public static string Enum_SmartWaitType_UntilPixelColor   { get { return ResourceManager.GetString("Enum_SmartWaitType_UntilPixelColor",   resourceCulture); } }
        public static string Node_SmartWait_WaitType             { get { return ResourceManager.GetString("Node_SmartWait_WaitType",             resourceCulture); } }
        public static string Node_SmartWait_Window               { get { return ResourceManager.GetString("Node_SmartWait_Window",               resourceCulture); } }
        public static string Node_SmartWait_Timeout              { get { return ResourceManager.GetString("Node_SmartWait_Timeout",              resourceCulture); } }
        public static string Node_SmartWait_PixelX               { get { return ResourceManager.GetString("Node_SmartWait_PixelX",               resourceCulture); } }
        public static string Node_SmartWait_PixelY               { get { return ResourceManager.GetString("Node_SmartWait_PixelY",               resourceCulture); } }
        public static string Node_SmartWait_Color                { get { return ResourceManager.GetString("Node_SmartWait_Color",                resourceCulture); } }
        public static string Node_AudioDevice_Name               { get { return ResourceManager.GetString("Node_AudioDevice_Name",               resourceCulture); } }
        public static string Node_AudioDevice_IsPlayback         { get { return ResourceManager.GetString("Node_AudioDevice_IsPlayback",         resourceCulture); } }

        public static string Nav_Twitch               { get { return ResourceManager.GetString("Nav_Twitch",               resourceCulture); } }
        public static string Twitch_Title             { get { return ResourceManager.GetString("Twitch_Title",             resourceCulture); } }
        public static string Twitch_ChannelLabel      { get { return ResourceManager.GetString("Twitch_ChannelLabel",      resourceCulture); } }
        public static string Twitch_UsernameLabel     { get { return ResourceManager.GetString("Twitch_UsernameLabel",     resourceCulture); } }
        public static string Twitch_OAuthLabel        { get { return ResourceManager.GetString("Twitch_OAuthLabel",        resourceCulture); } }
        public static string Twitch_OAuthHint         { get { return ResourceManager.GetString("Twitch_OAuthHint",         resourceCulture); } }
        public static string Twitch_StatusConnected   { get { return ResourceManager.GetString("Twitch_StatusConnected",   resourceCulture); } }
        public static string Twitch_StatusDisconnected{ get { return ResourceManager.GetString("Twitch_StatusDisconnected",resourceCulture); } }
        public static string Twitch_ConnectBtn        { get { return ResourceManager.GetString("Twitch_ConnectBtn",        resourceCulture); } }
        public static string Twitch_DisconnectBtn     { get { return ResourceManager.GetString("Twitch_DisconnectBtn",     resourceCulture); } }
        public static string Twitch_SaveBtn           { get { return ResourceManager.GetString("Twitch_SaveBtn",           resourceCulture); } }
        public static string Twitch_TtsPermissionHint { get { return ResourceManager.GetString("Twitch_TtsPermissionHint", resourceCulture); } }

        public static string Enum_LogicDataType_Text        { get { return ResourceManager.GetString("Enum_LogicDataType_Text",        resourceCulture); } }
        public static string Enum_LogicDataType_Number      { get { return ResourceManager.GetString("Enum_LogicDataType_Number",      resourceCulture); } }
        public static string Enum_LogicDataType_Boolean     { get { return ResourceManager.GetString("Enum_LogicDataType_Boolean",     resourceCulture); } }
        public static string Enum_LogicCompareType_Equals      { get { return ResourceManager.GetString("Enum_LogicCompareType_Equals",      resourceCulture); } }
        public static string Enum_LogicCompareType_NotEquals   { get { return ResourceManager.GetString("Enum_LogicCompareType_NotEquals",   resourceCulture); } }
        public static string Enum_LogicCompareType_GreaterThan { get { return ResourceManager.GetString("Enum_LogicCompareType_GreaterThan", resourceCulture); } }
        public static string Enum_LogicCompareType_LessThan    { get { return ResourceManager.GetString("Enum_LogicCompareType_LessThan",    resourceCulture); } }
        public static string Enum_LogicCompareType_Contains    { get { return ResourceManager.GetString("Enum_LogicCompareType_Contains",    resourceCulture); } }
        public static string Node_Branch_DataType    { get { return ResourceManager.GetString("Node_Branch_DataType",    resourceCulture); } }
        public static string Node_Branch_CompareType { get { return ResourceManager.GetString("Node_Branch_CompareType", resourceCulture); } }
        public static string Node_Branch_TargetValue { get { return ResourceManager.GetString("Node_Branch_TargetValue", resourceCulture); } }
        public static string Node_Branch_IgnoreCase  { get { return ResourceManager.GetString("Node_Branch_IgnoreCase",  resourceCulture); } }
        public static string Toolbox_LogicBranchNode_Name { get { return ResourceManager.GetString("Toolbox_LogicBranchNode_Name", resourceCulture); } }
        public static string Toolbox_LogicBranchNode_Desc { get { return ResourceManager.GetString("Toolbox_LogicBranchNode_Desc", resourceCulture); } }

        public static string Toolbox_VisionOcrNode_Name     { get { return ResourceManager.GetString("Toolbox_VisionOcrNode_Name",     resourceCulture); } }
        public static string Toolbox_VisionOcrNode_Desc     { get { return ResourceManager.GetString("Toolbox_VisionOcrNode_Desc",     resourceCulture); } }
        public static string Toolbox_WinTranslateNode_Name  { get { return ResourceManager.GetString("Toolbox_WinTranslateNode_Name",  resourceCulture); } }
        public static string Toolbox_WinTranslateNode_Desc  { get { return ResourceManager.GetString("Toolbox_WinTranslateNode_Desc",  resourceCulture); } }
        public static string Node_OcrImagePath              { get { return ResourceManager.GetString("Node_OcrImagePath",              resourceCulture); } }
        public static string Node_OcrLanguage               { get { return ResourceManager.GetString("Node_OcrLanguage",               resourceCulture); } }
        public static string Node_WinTranslateSourceText    { get { return ResourceManager.GetString("Node_WinTranslateSourceText",    resourceCulture); } }
        public static string Node_WinTranslateTargetCode   { get { return ResourceManager.GetString("Node_WinTranslateTargetCode",   resourceCulture); } }
        public static string Node_WinTranslateResult           { get { return ResourceManager.GetString("Node_WinTranslateResult",           resourceCulture); } }
        public static string Toolbox_LogicSequenceNode_Name    { get { return ResourceManager.GetString("Toolbox_LogicSequenceNode_Name",    resourceCulture); } }
        public static string Toolbox_LogicSequenceNode_Desc    { get { return ResourceManager.GetString("Toolbox_LogicSequenceNode_Desc",    resourceCulture); } }
        public static string Node_Sequence_StepsLabel             { get { return ResourceManager.GetString("Node_Sequence_StepsLabel",             resourceCulture); } }
        public static string Toolbox_LogicQueueBlockNode_Name     { get { return ResourceManager.GetString("Toolbox_LogicQueueBlockNode_Name",     resourceCulture); } }
        public static string Toolbox_LogicQueueBlockNode_Desc     { get { return ResourceManager.GetString("Toolbox_LogicQueueBlockNode_Desc",     resourceCulture); } }
        public static string Node_QueueBlock_WaitFullChain        { get { return ResourceManager.GetString("Node_QueueBlock_WaitFullChain",        resourceCulture); } }
        public static string Node_QueueBlock_WaitNodesCount       { get { return ResourceManager.GetString("Node_QueueBlock_WaitNodesCount",       resourceCulture); } }
        public static string Toolbox_BypassQueueNode_Name         { get { return ResourceManager.GetString("Toolbox_BypassQueueNode_Name",         resourceCulture); } }
        public static string Toolbox_BypassQueueNode_Desc         { get { return ResourceManager.GetString("Toolbox_BypassQueueNode_Desc",         resourceCulture); } }

        public static string Nav_Obs               { get { return ResourceManager.GetString("Nav_Obs",               resourceCulture); } }
        public static string Obs_Title             { get { return ResourceManager.GetString("Obs_Title",             resourceCulture); } }
        public static string Obs_UrlLabel          { get { return ResourceManager.GetString("Obs_UrlLabel",          resourceCulture); } }
        public static string Obs_IpLabel           { get { return ResourceManager.GetString("Obs_IpLabel",           resourceCulture); } }
        public static string Obs_PortLabel         { get { return ResourceManager.GetString("Obs_PortLabel",         resourceCulture); } }
        public static string Obs_PasswordLabel     { get { return ResourceManager.GetString("Obs_PasswordLabel",     resourceCulture); } }
        public static string Obs_StatusConnected   { get { return ResourceManager.GetString("Obs_StatusConnected",   resourceCulture); } }
        public static string Obs_StatusDisconnected{ get { return ResourceManager.GetString("Obs_StatusDisconnected",resourceCulture); } }
        public static string Obs_ConnectBtn        { get { return ResourceManager.GetString("Obs_ConnectBtn",        resourceCulture); } }
        public static string Obs_DisconnectBtn     { get { return ResourceManager.GetString("Obs_DisconnectBtn",     resourceCulture); } }
        public static string Obs_AutoConnect        { get { return ResourceManager.GetString("Obs_AutoConnect",        resourceCulture); } }
        public static string Obs_AutoReconnect     { get { return ResourceManager.GetString("Obs_AutoReconnect",     resourceCulture); } }
        public static string Obs_ProtocolVersion   { get { return ResourceManager.GetString("Obs_ProtocolVersion",   resourceCulture); } }
        public static string Obs_SaveBtn           { get { return ResourceManager.GetString("Obs_SaveBtn",           resourceCulture); } }
        public static string Obs_ScenesLabel       { get { return ResourceManager.GetString("Obs_ScenesLabel",       resourceCulture); } }
        public static string Obs_RefreshScenesBtn  { get { return ResourceManager.GetString("Obs_RefreshScenesBtn",  resourceCulture); } }

        public static string Toolbox_Category_GuardianLogic   { get { return ResourceManager.GetString("Toolbox_Category_GuardianLogic",   resourceCulture); } }
        public static string Toolbox_MacroPolicyNode_Name     { get { return ResourceManager.GetString("Toolbox_MacroPolicyNode_Name",     resourceCulture); } }
        public static string Toolbox_MacroPolicyNode_Desc     { get { return ResourceManager.GetString("Toolbox_MacroPolicyNode_Desc",     resourceCulture); } }
        public static string Toolbox_SynchronizerNode_Name    { get { return ResourceManager.GetString("Toolbox_SynchronizerNode_Name",    resourceCulture); } }
        public static string Toolbox_SynchronizerNode_Desc    { get { return ResourceManager.GetString("Toolbox_SynchronizerNode_Desc",    resourceCulture); } }
        public static string Toolbox_MacroResetNode_Name      { get { return ResourceManager.GetString("Toolbox_MacroResetNode_Name",      resourceCulture); } }
        public static string Toolbox_MacroResetNode_Desc      { get { return ResourceManager.GetString("Toolbox_MacroResetNode_Desc",      resourceCulture); } }
        public static string Blueprint_PortTriggerIn          { get { return ResourceManager.GetString("Blueprint_PortTriggerIn",          resourceCulture); } }
        public static string Blueprint_PortDataIn             { get { return ResourceManager.GetString("Blueprint_PortDataIn",             resourceCulture); } }
        public static string Blueprint_PortCustomData         { get { return ResourceManager.GetString("Blueprint_PortCustomData",         resourceCulture); } }
        public static string Blueprint_PortBlackBox           { get { return ResourceManager.GetString("Blueprint_PortBlackBox",           resourceCulture); } }
    }
}
